# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\深海\实船性能测试\PerformanceTest\UI\voyage_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(653, 66)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("color: rgb(255, 85, 0);\n"
"font: 75 9pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 5, 1, 2)
        self.waterDepth = QtWidgets.QLineEdit(Form)
        self.waterDepth.setObjectName("waterDepth")
        self.gridLayout.addWidget(self.waterDepth, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 5, 1, 1)
        self.windDirection = QtWidgets.QLineEdit(Form)
        self.windDirection.setObjectName("windDirection")
        self.gridLayout.addWidget(self.windDirection, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 3, 1, 1)
        self.load = QtWidgets.QLineEdit(Form)
        self.load.setObjectName("load")
        self.gridLayout.addWidget(self.load, 1, 2, 1, 1)
        self.windSpeed = QtWidgets.QLineEdit(Form)
        self.windSpeed.setObjectName("windSpeed")
        self.gridLayout.addWidget(self.windSpeed, 1, 8, 1, 1)
        self.filePath = QtWidgets.QLineEdit(Form)
        self.filePath.setObjectName("filePath")
        self.gridLayout.addWidget(self.filePath, 0, 1, 1, 4)
        self.resultButton = QtWidgets.QPushButton(Form)
        self.resultButton.setObjectName("resultButton")
        self.gridLayout.addWidget(self.resultButton, 0, 8, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600; color:#ff5500;\">工况1：</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "浏览文件"))
        self.label_4.setText(_translate("Form", "相对风速："))
        self.label_2.setText(_translate("Form", "M/E Load："))
        self.label_5.setText(_translate("Form", "水深"))
        self.label_3.setText(_translate("Form", "相对风向："))
        self.resultButton.setText(_translate("Form", "查看分析结果"))
